### PR TITLE
fix: resolved issue related to GET methods where the text response is…

### LINKED ISSUE #32: [BUG]: Getting undefined result when calling findBillableMetric
When calling get request methods of SDK like `findBillableMetric`  or `findPlan` this [line](https://github.com/getlago/lago-nodejs-client/blob/9a78def21c299b4ba09a28fb70a92c026424815c/lib/client.js#L50) is executed , which returns the JSON Object `{"billable_metric":{"lago_id":"fcb0e1b8-acd7-4c1a-9b39-2bd63ef6f6d8","name":"User Start","code":"star","description":"","aggregation_type":"count_agg","created_at":"2022-11-11T13:17:09Z","field_name":null,"group":{}}}` where as the caller expects the response to be a Javascript object and when it tries to read property from the object `res.billable_metric` https://github.com/getlago/lago-nodejs-client/blob/9a78def21c299b4ba09a28fb70a92c026424815c/lib/client.js#L265 it returns undefined.

### PR DESCRIPTION
**Pull request by huzaifaali14**
Closes #32

### CODE REVIEW

File: lib/client.js [hunk 1]
```diff
@@ -44,10 +45,14 @@ export default class Client {
         }
 
         let data;
-        await fetch(fullUrl, options).then(response => {
+        await fetch(fullUrl, options).then(async (response) => {
             if (response.ok) {
                 if (method === 'get') {
-                    data = response.text();
+                    data = await response.text();
```
Comment (lovrocolic) [inline lib/client.js:51]: I guess we should also use the `await` statement in the line 60 now (`post` block)

Comment (huzaifaali14) [reply lib/client.js:51]: @lovrocolic I guess its not required. Since either way function is returning a promise at the end.

**Review by lovrocolic — APPROVED** [review]

File: lib/client.js (hunk 1 above)
Comment (jdenquin) [inline lib/client.js:51]: could it be different than JSON? the API always return a JSON format

File: lib/client.js [hunk 2]
```diff
@@ -44,10 +45,14 @@ export default class Client {
...
+
+                    if (isJSON(data)) {
```
Comment (cursan-a) [inline lib/client.js:53]: I think it should be better to use the header of response : `response.headers.get('content-type')` and checking if it contains `application/json`. It will avoid using `JSON.parse`
